import type { Env,FulfillmentMessage } from './types.js';
import { route } from './router.js';
import { fulfillOrder,reconcileOrder } from './commerce/fulfillment.js';
import { getProvider } from './providers/index.js';
import { audit } from './lib/audit.js';
import { retrieveStripeCheckout } from './stripe/client.js';

export default{fetch(request:Request,env:Env,ctx:ExecutionContext):Promise<Response>{return route(request,env,ctx);},async queue(batch:MessageBatch<FulfillmentMessage>,env:Env):Promise<void>{for(const message of batch.messages){try{if(message.body.type==='FULFILL_ORDER'&&message.body.orderId)await fulfillOrder(env,message.body.orderId);else if(message.body.type==='RECONCILE_ORDER'&&message.body.orderId)await reconcileOrder(env,message.body.orderId);else if(message.body.type==='CLEANUP_QUOTE'&&message.body.quoteId)await cleanupQuote(env,message.body.quoteId);message.ack();}catch(error){console.error('Queue job failed',message.body,error);message.retry({delaySeconds:Math.min(3600,Math.max(60,60*2**Math.min(message.attempts,5)))});}}},async scheduled(_controller:ScheduledController,env:Env,ctx:ExecutionContext):Promise<void>{ctx.waitUntil(runScheduledMaintenance(env));}};

function days(value:string|undefined,fallback:number,min:number,max:number){const parsed=Number(value);return Number.isFinite(parsed)?Math.min(max,Math.max(min,Math.floor(parsed))):fallback;}
async function runScheduledMaintenance(env:Env):Promise<void>{const now=new Date().toISOString();
 const expired=await env.COMMERCE_DB.prepare(`SELECT q.id FROM shipping_quotes q LEFT JOIN orders o ON o.id=q.order_id WHERE (q.status='open' AND q.expires_at<?) OR (q.status='reserved' AND ((o.id IS NULL AND q.expires_at<?) OR (o.stripe_checkout_session_id IS NULL AND q.expires_at<?) OR (o.payment_status<>'paid' AND o.status IN ('expired','cancelled')))) LIMIT 200`).bind(now,now,now).all<{id:string}>();for(const row of expired.results||[])await env.FULFILLMENT_QUEUE.send({type:'CLEANUP_QUOTE',quoteId:row.id});
 const needsSubmission=await env.COMMERCE_DB.prepare(`SELECT id FROM orders WHERE payment_status='paid' AND status NOT IN ('cancelled','expired') AND exception_code IS NULL AND fulfillment_status IN ('unfulfilled','queued') ORDER BY updated_at ASC LIMIT 100`).all<{id:string}>();for(const row of needsSubmission.results||[])await env.FULFILLMENT_QUEUE.send({type:'FULFILL_ORDER',orderId:row.id});
 const needsReconcile=await env.COMMERCE_DB.prepare(`SELECT DISTINCT order_id AS id FROM fulfillment_groups WHERE provider_order_id IS NOT NULL AND status NOT IN ('delivered','cancelled') ORDER BY updated_at ASC LIMIT 100`).all<{id:string}>();for(const row of needsReconcile.results||[])await env.FULFILLMENT_QUEUE.send({type:'RECONCILE_ORDER',orderId:row.id});
 const stale=await env.COMMERCE_DB.prepare(`SELECT id,order_id,provider FROM fulfillment_groups WHERE status='submitting' AND provider_order_id IS NULL AND COALESCE(submission_started_at,updated_at)<? LIMIT 100`).bind(new Date(Date.now()-60*60_000).toISOString()).all<{id:string;order_id:string;provider:string}>();for(const group of stale.results||[]){if(group.provider==='kunaki'){const result=await env.COMMERCE_DB.prepare(`UPDATE fulfillment_groups SET status='exception',last_error=?,submission_token=NULL,submission_started_at=NULL,updated_at=? WHERE id=? AND status='submitting' AND provider_order_id IS NULL`).bind('Submission was interrupted before a Kunaki OrderId was persisted. Manual provider review is required before any resubmission.',now,group.id).run();if(Number(result.meta?.changes||0)===1)await audit(env,{actorType:'system',action:'fulfillment.ambiguous_submission',entityType:'fulfillment_group',entityId:group.id,metadata:{provider:'kunaki'}});}else if(group.provider==='spreadconnect'){const result=await env.COMMERCE_DB.prepare(`UPDATE fulfillment_groups SET status='exception',last_error=?,submission_token=NULL,submission_started_at=NULL,updated_at=? WHERE id=? AND status='submitting' AND provider_order_id IS NULL`).bind('Spreadconnect submission lease expired. Safe retry queued against the existing draft order.',now,group.id).run();if(Number(result.meta?.changes||0)===1)await env.FULFILLMENT_QUEUE.send({type:'FULFILL_ORDER',orderId:group.order_id});}}
 await env.COMMERCE_DB.prepare(`UPDATE webhook_events SET processing_token=NULL,processing_started_at=NULL WHERE processed_at IS NULL AND processing_started_at<?`).bind(new Date(Date.now()-15*60_000).toISOString()).run();await env.COMMERCE_DB.prepare(`DELETE FROM webhook_events WHERE processed_at IS NOT NULL AND received_at<?`).bind(new Date(Date.now()-30*24*60*60_000).toISOString()).run();await redactExpiredPii(env,now);
}

async function redactExpiredPii(env:Env,now:string):Promise<void>{const unpaidDays=days(env.UNPAID_PII_RETENTION_DAYS,7,1,90),customerDays=days(env.CUSTOMER_PII_RETENTION_DAYS,365,30,3650),unpaidCutoff=new Date(Date.now()-unpaidDays*86400000).toISOString(),customerCutoff=new Date(Date.now()-customerDays*86400000).toISOString();
 await env.COMMERCE_DB.batch([
  env.COMMERCE_DB.prepare(`UPDATE orders SET customer_email='[redacted]',customer_phone='[redacted]',address_json='{}',stripe_address_json=NULL,stripe_checkout_url=NULL,pii_redacted_at=?,updated_at=updated_at WHERE pii_redacted_at IS NULL AND payment_status<>'paid' AND status IN ('expired','cancelled','payment_failed') AND updated_at<?`).bind(now,unpaidCutoff),
  env.COMMERCE_DB.prepare(`UPDATE orders SET customer_email='[redacted]',customer_phone='[redacted]',address_json='{}',stripe_address_json=NULL,stripe_checkout_url=NULL,pii_redacted_at=?,updated_at=updated_at WHERE pii_redacted_at IS NULL AND payment_status='paid' AND status IN ('complete','cancelled') AND updated_at<?`).bind(now,customerCutoff),
  env.COMMERCE_DB.prepare(`UPDATE shipping_quotes SET address_json='{}',contact_json='{}',pii_redacted_at=? WHERE pii_redacted_at IS NULL AND ((status IN ('expired','cancelled') AND created_at<?) OR order_id IN (SELECT id FROM orders WHERE pii_redacted_at IS NOT NULL))`).bind(now,unpaidCutoff),
  env.COMMERCE_DB.prepare(`UPDATE shipments SET carrier=NULL,tracking_number=NULL,tracking_url=NULL WHERE order_id IN (SELECT id FROM orders WHERE pii_redacted_at IS NOT NULL)`),
  env.COMMERCE_DB.prepare(`UPDATE refunds SET reason=NULL,last_error=NULL WHERE order_id IN (SELECT id FROM orders WHERE pii_redacted_at IS NOT NULL)`),
  env.COMMERCE_DB.prepare(`UPDATE fulfillment_groups SET last_error=NULL WHERE order_id IN (SELECT id FROM orders WHERE pii_redacted_at IS NOT NULL)`),
  env.COMMERCE_DB.prepare(`UPDATE fulfillment_attempts SET error=NULL WHERE order_id IN (SELECT id FROM orders WHERE pii_redacted_at IS NOT NULL)`),
  env.COMMERCE_DB.prepare(`UPDATE audit_log SET metadata_json=NULL WHERE entity_type='order' AND entity_id IN (SELECT id FROM orders WHERE pii_redacted_at IS NOT NULL)`)
 ]);
}

async function cleanupQuote(env:Env,quoteId:string):Promise<void>{const quote=await env.COMMERCE_DB.prepare(`SELECT provider_quotes_json,order_id,status,expires_at FROM shipping_quotes WHERE id=?`).bind(quoteId).first<{provider_quotes_json:string;order_id:string|null;status:string;expires_at:string}>();if(!quote||!['open','reserved'].includes(quote.status))return;
 if(quote.order_id){const order=await env.COMMERCE_DB.prepare(`SELECT payment_status,status,stripe_checkout_session_id FROM orders WHERE id=?`).bind(quote.order_id).first<{payment_status:string;status:string;stripe_checkout_session_id:string|null}>();if(order?.payment_status==='paid')return;if(order?.stripe_checkout_session_id){const stripe=await retrieveStripeCheckout(env,order.stripe_checkout_session_id);if(stripe.paymentStatus==='paid'||stripe.status==='complete')return;if(stripe.status!=='expired')return;}else if(Date.parse(quote.expires_at)>Date.now()&&order?.status!=='cancelled')return;if(order&&order.status!=='cancelled')await env.COMMERCE_DB.prepare(`UPDATE orders SET status='expired',updated_at=? WHERE id=? AND payment_status<>'paid'`).bind(new Date().toISOString(),quote.order_id).run();}
 else if(Date.parse(quote.expires_at)>Date.now())return;
 const providers=JSON.parse(quote.provider_quotes_json) as Array<{provider:'kunaki'|'spreadconnect';draftOrderId?:string}>;for(const provider of providers){if(quote.order_id){const latest=await env.COMMERCE_DB.prepare('SELECT payment_status FROM orders WHERE id=?').bind(quote.order_id).first<{payment_status:string}>();if(latest?.payment_status==='paid')return;}if(provider.draftOrderId)await getProvider(provider.provider).cleanupDraft?.(env,provider.draftOrderId);}if(quote.order_id){const latest=await env.COMMERCE_DB.prepare('SELECT payment_status FROM orders WHERE id=?').bind(quote.order_id).first<{payment_status:string}>();if(latest?.payment_status==='paid')return;}await env.COMMERCE_DB.prepare(`UPDATE shipping_quotes SET status='expired' WHERE id=? AND status IN ('open','reserved')`).bind(quoteId).run();}
