import type { Address, Env, HheShippingOption } from './types.js';
import { listCatalog, resolveCart } from './repositories/catalog.js';
import { createShippingQuote } from './commerce/shipping.js';
import { createCheckout } from './commerce/checkout.js';
import { getPublicOrder } from './repositories/orders.js';
import { corsHeaders, errorResponse, json, readJson, readTextLimited } from './lib/http.js';
import { badRequest, notFound, unauthorized } from './lib/errors.js';
import { verifyStripeWebhook } from './security/stripe-webhook.js';
import { verifySpreadconnectWebhook } from './security/spreadconnect-webhook.js';
import { safeEqual, sha256Hex } from './lib/crypto.js';
import { fulfillmentAddressMatches, stripeShippingAddress } from './lib/address.js';
import { audit } from './lib/audit.js';
import { enforceAdminRateLimit, enforcePublicRateLimit } from './security/rate-limit.js';
import { verifyTurnstile } from './security/turnstile.js';
import { claimWebhook, failWebhook, finishWebhook } from './lib/webhooks.js';
import { adminSummary, addManualShipment, attachProviderOrder, cancelFulfillment, cancelOrder, getAdminOrder, listAdminOrders, listAudit, listSettings, resolveAddressException, retryFulfillment, saveProduct, saveVariant, setCatalogActive, updateSettings } from './admin/service.js';
import { createRefund, updateRefundFromWebhook } from './stripe/refunds.js';

function publicQuote(result:{quoteId:string;expiresAt:string;options:HheShippingOption[];reused?:boolean}){return{quoteId:result.quoteId,expiresAt:result.expiresAt,reused:result.reused||undefined,options:result.options.map(option=>({id:option.id,name:option.name,price:option.price,currency:option.currency,minDays:option.minDays,maxDays:option.maxDays}))};}

export async function route(request:Request,env:Env,ctx:ExecutionContext):Promise<Response>{
 const url=new URL(request.url),path=url.pathname.replace(/\/+$/,'')||'/';if(request.method==='OPTIONS')return new Response(null,{status:204,headers:corsHeaders(request,env)});
 try{
  if(request.method==='GET'&&path==='/health')return json({ok:true,service:'hhe-commerce',version:'0.2.2-rc1.2'});
  if(request.method==='GET'&&path==='/api/catalog')return json({products:await listCatalog(env)});
  if(request.method==='POST'&&path==='/api/shipping/quote'){const body=await readJson<{items:Array<{sku:string;quantity:number}>;address:Address;contact:{email:string;phone:string}}>(request);await enforcePublicRateLimit(env,request,'shipping-quote',body.contact?.email);await verifyTurnstile(env,request,'shipping_quote');const items=await resolveCart(env,body.items);return json(publicQuote(await createShippingQuote(env,items,body.address,body.contact,request.headers.get('idempotency-key')||undefined)),201);}
  if(request.method==='POST'&&path==='/api/checkout/create'){const body=await readJson<{quoteId:string;shippingOptionId:string}>(request);if(!body.quoteId||!body.shippingOptionId)throw badRequest('quoteId and shippingOptionId are required');await enforcePublicRateLimit(env,request,'checkout',body.quoteId);return json(await createCheckout(env,body.quoteId,body.shippingOptionId),201);}
  const publicOrder=path.match(/^\/api\/orders\/([^/]+)$/);if(request.method==='GET'&&publicOrder){const token=request.headers.get('x-hhe-order-token')||'';await enforcePublicRateLimit(env,request,'order-read',`${publicOrder[1]}:${token}`);return json(await getPublicOrder(env,decodeURIComponent(publicOrder[1]),token));}
  if(request.method==='POST'&&path==='/api/webhooks/stripe')return handleStripeWebhook(request,env,ctx);
  if(request.method==='POST'&&path==='/api/webhooks/spreadconnect')return handleSpreadconnectWebhook(request,env,ctx);
  if(path.startsWith('/api/admin/')){await requireAdmin(request,env,path);return routeAdmin(request,env,url,path);}throw notFound('Route not found');
 }catch(error){const response=errorResponse(error);for(const[key,value]of Object.entries(corsHeaders(request,env)))response.headers.set(key,String(value));return response;}
}
async function requireAdmin(request:Request,env:Env,scope:string){await enforceAdminRateLimit(env,request,scope);const header=request.headers.get('authorization')||'',expected=`Bearer ${env.ADMIN_API_KEY}`;if(!env.ADMIN_API_KEY||env.ADMIN_API_KEY.length<32||!safeEqual(header,expected))throw unauthorized();}

async function routeAdmin(request:Request,env:Env,url:URL,path:string):Promise<Response>{
 if(request.method==='GET'&&path==='/api/admin/summary')return json(await adminSummary(env));if(request.method==='GET'&&path==='/api/admin/orders')return json(await listAdminOrders(env,{status:url.searchParams.get('status')||undefined,provider:url.searchParams.get('provider')||undefined,limit:Number(url.searchParams.get('limit')||50),cursor:url.searchParams.get('cursor')||undefined}));
 const order=path.match(/^\/api\/admin\/orders\/([^/]+)$/);if(request.method==='GET'&&order)return json(await getAdminOrder(env,decodeURIComponent(order[1])));const cancelOrderMatch=path.match(/^\/api\/admin\/orders\/([^/]+)\/cancel$/);if(request.method==='POST'&&cancelOrderMatch)return json(await cancelOrder(env,decodeURIComponent(cancelOrderMatch[1])));const reconcile=path.match(/^\/api\/admin\/orders\/([^/]+)\/reconcile$/);if(request.method==='POST'&&reconcile){await env.FULFILLMENT_QUEUE.send({type:'RECONCILE_ORDER',orderId:decodeURIComponent(reconcile[1])});await audit(env,{actorType:'admin',actorId:'admin-api',action:'order.reconcile_queued',entityType:'order',entityId:decodeURIComponent(reconcile[1])});return json({queued:true},202);}
 const resolveAddress=path.match(/^\/api\/admin\/orders\/([^/]+)\/resolve-address$/);if(request.method==='POST'&&resolveAddress)return json(await resolveAddressException(env,decodeURIComponent(resolveAddress[1])),202);const refund=path.match(/^\/api\/admin\/orders\/([^/]+)\/refund$/);if(request.method==='POST'&&refund){const body=await readJson<{amount?:number;reason?:string}>(request);return json(await createRefund(env,{orderId:decodeURIComponent(refund[1]),amount:body.amount,reason:body.reason,requestKey:request.headers.get('idempotency-key')||''}),201);}
 const retry=path.match(/^\/api\/admin\/fulfillments\/([^/]+)\/retry$/);if(request.method==='POST'&&retry){const body=await readJson<{duplicateRiskToken?:string}>(request);return json(await retryFulfillment(env,decodeURIComponent(retry[1]),body.duplicateRiskToken),202);}const attach=path.match(/^\/api\/admin\/fulfillments\/([^/]+)\/attach-provider-order$/);if(request.method==='POST'&&attach){const body=await readJson<{providerOrderId:string}>(request);return json(await attachProviderOrder(env,decodeURIComponent(attach[1]),body.providerOrderId),202);}const cancel=path.match(/^\/api\/admin\/fulfillments\/([^/]+)\/cancel$/);if(request.method==='POST'&&cancel)return json(await cancelFulfillment(env,decodeURIComponent(cancel[1])));const shipment=path.match(/^\/api\/admin\/fulfillments\/([^/]+)\/shipments$/);if(request.method==='POST'&&shipment){const body=await readJson<{carrier?:string;trackingNumber?:string;trackingUrl?:string;status?:string}>(request);return json(await addManualShipment(env,decodeURIComponent(shipment[1]),body),201);}
 if(request.method==='GET'&&path==='/api/admin/settings')return json({settings:await listSettings(env)});if(request.method==='POST'&&path==='/api/admin/settings')return json({settings:await updateSettings(env,await readJson<Record<string,unknown>>(request))});if(request.method==='POST'&&path==='/api/admin/products')return json(await saveProduct(env,await readJson<any>(request)),201);if(request.method==='POST'&&path==='/api/admin/variants')return json(await saveVariant(env,await readJson<any>(request)),201);
 const productStatus=path.match(/^\/api\/admin\/products\/([^/]+)\/status$/);if(request.method==='POST'&&productStatus){const body=await readJson<{active:boolean}>(request);return json(await setCatalogActive(env,'product',decodeURIComponent(productStatus[1]),Boolean(body.active)));}const variantStatus=path.match(/^\/api\/admin\/variants\/([^/]+)\/status$/);if(request.method==='POST'&&variantStatus){const body=await readJson<{active:boolean}>(request);return json(await setCatalogActive(env,'variant',decodeURIComponent(variantStatus[1]),Boolean(body.active)));}if(request.method==='GET'&&path==='/api/admin/audit')return json(await listAudit(env,{limit:Number(url.searchParams.get('limit')||100),cursor:url.searchParams.get('cursor')||undefined,action:url.searchParams.get('action')||undefined}));throw notFound('Admin route not found');
}

interface PaymentOrderRow{id:string;order_number:string;address_json:string;payment_status:string;fulfillment_status:string;stripe_checkout_session_id:string|null;stripe_payment_intent_id:string|null;currency:string;subtotal:number;shipping_total:number;}
function paymentIntegrityErrors(order:PaymentOrderRow,session:Record<string,any>):string[]{const errors:string[]=[],sessionId=String(session.id||''),tax=Number(session.total_details?.amount_tax??NaN),total=Number(session.amount_total??NaN),subtotal=Number(session.amount_subtotal??NaN),shipping=Number(session.total_details?.amount_shipping??NaN);if(!sessionId)errors.push('missing_session_id');if(!order.stripe_checkout_session_id||order.stripe_checkout_session_id!==sessionId)errors.push('checkout_session_id_mismatch');if(String(session.client_reference_id||'')!==order.id)errors.push('client_reference_id_mismatch');if(String(session.metadata?.order_id||'')!==order.id)errors.push('metadata_order_id_mismatch');if(String(session.metadata?.order_number||'')!==order.order_number)errors.push('metadata_order_number_mismatch');if(String(session.currency||'').toLowerCase()!==order.currency.toLowerCase())errors.push('currency_mismatch');if(!Number.isSafeInteger(subtotal)||subtotal!==order.subtotal)errors.push('subtotal_mismatch');if(!Number.isSafeInteger(shipping)||shipping!==order.shipping_total)errors.push('shipping_total_mismatch');if(!Number.isSafeInteger(tax)||tax<0||!Number.isSafeInteger(total)||total!==order.subtotal+order.shipping_total+tax)errors.push('grand_total_mismatch');if(!session.payment_intent)errors.push('missing_payment_intent');return errors;}

async function handleStripeWebhook(request:Request,env:Env,ctx:ExecutionContext):Promise<Response>{
 const raw=await readTextLimited(request,1024*1024);await verifyStripeWebhook(raw,request.headers.get('stripe-signature'),env.STRIPE_WEBHOOK_SECRET);const event=JSON.parse(raw) as Record<string,any>,eventId=String(event.id||await sha256Hex(raw)),payloadHash=await sha256Hex(raw);const claim=await claimWebhook(env,'stripe',eventId,String(event.type||''),payloadHash);if(!claim)return json({received:true});
 try{
  if(event.type==='checkout.session.completed'||event.type==='checkout.session.async_payment_succeeded'){const session=event.data?.object||{},isPaid=event.type==='checkout.session.async_payment_succeeded'||session.payment_status==='paid',orderId=String(session.client_reference_id||session.metadata?.order_id||'');if(orderId&&isPaid){const row=await env.COMMERCE_DB.prepare(`SELECT id,order_number,address_json,payment_status,fulfillment_status,stripe_checkout_session_id,stripe_payment_intent_id,currency,subtotal,shipping_total FROM orders WHERE id=?`).bind(orderId).first<PaymentOrderRow>();if(row&&row.payment_status!=='paid'){const tax=Number(session.total_details?.amount_tax||0),total=Number(session.amount_total||0),paymentIntent=session.payment_intent?String(session.payment_intent):null,sessionId=String(session.id||''),errors=paymentIntegrityErrors(row,session);if(paymentIntent){const used=await env.COMMERCE_DB.prepare('SELECT id FROM orders WHERE stripe_payment_intent_id=? AND id<>?').bind(paymentIntent,orderId).first<{id:string}>();if(used)errors.push('payment_intent_reused');}
    if(errors.length){const collision=errors.includes('payment_intent_reused');await env.COMMERCE_DB.prepare(`UPDATE orders SET status='exception',payment_status='paid',fulfillment_status='exception',tax_total=?,grand_total=?,stripe_payment_intent_id=CASE WHEN ? THEN stripe_payment_intent_id ELSE ? END,exception_code='payment_integrity_mismatch',exception_detail=?,updated_at=? WHERE id=?`).bind(tax,total,collision?1:0,paymentIntent,`Stripe payment session failed integrity validation: ${errors.join(', ')}`,new Date().toISOString(),orderId).run();await audit(env,{actorType:'stripe',actorId:eventId,action:'payment.integrity_exception',entityType:'order',entityId:orderId,metadata:{errors,sessionId}});
    }else{const quoted=JSON.parse(row.address_json) as Address,paidAddress=stripeShippingAddress(session),mismatch=!paidAddress||!fulfillmentAddressMatches(quoted,paidAddress);if(mismatch){const code=paidAddress?'shipping_address_mismatch':'shipping_address_missing';await env.COMMERCE_DB.prepare(`UPDATE orders SET status='exception',payment_status='paid',fulfillment_status='exception',tax_total=?,grand_total=?,stripe_payment_intent_id=?,stripe_address_json=?,exception_code=?,exception_detail=?,updated_at=? WHERE id=?`).bind(tax,total,paymentIntent,paidAddress?JSON.stringify(paidAddress):null,code,paidAddress?'Stripe shipping address differs from the quoted fulfillment address':'Stripe did not return the required shipping address',new Date().toISOString(),orderId).run();await audit(env,{actorType:'stripe',actorId:eventId,action:'payment.address_exception',entityType:'order',entityId:orderId,metadata:{code}});}else{await env.COMMERCE_DB.prepare(`UPDATE orders SET status='paid',payment_status='paid',tax_total=?,grand_total=?,stripe_payment_intent_id=?,stripe_address_json=NULL,exception_code=NULL,exception_detail=NULL,updated_at=? WHERE id=?`).bind(tax,total,paymentIntent,new Date().toISOString(),orderId).run();await audit(env,{actorType:'stripe',actorId:eventId,action:'payment.succeeded',entityType:'order',entityId:orderId,metadata:{paymentIntent,total,tax,sessionId}});ctx.waitUntil(env.FULFILLMENT_QUEUE.send({type:'FULFILL_ORDER',orderId}));}}}}
  }else if(event.type==='checkout.session.async_payment_failed'){const session=event.data?.object||{},orderId=String(session.client_reference_id||session.metadata?.order_id||''),sessionId=String(session.id||'');if(orderId&&sessionId)await env.COMMERCE_DB.prepare(`UPDATE orders SET status='payment_failed',payment_status='failed',updated_at=? WHERE id=? AND stripe_checkout_session_id=? AND payment_status<>'paid'`).bind(new Date().toISOString(),orderId,sessionId).run();
  }else if(event.type==='checkout.session.expired'){const session=event.data?.object||{},orderId=String(session.client_reference_id||session.metadata?.order_id||''),sessionId=String(session.id||'');if(orderId&&sessionId)await env.COMMERCE_DB.prepare(`UPDATE orders SET status='expired',updated_at=? WHERE id=? AND stripe_checkout_session_id=? AND payment_status<>'paid'`).bind(new Date().toISOString(),orderId,sessionId).run();
  }else if(event.type==='refund.updated'||event.type==='refund.created'||event.type==='refund.failed')await updateRefundFromWebhook(env,event.data?.object||{});
  await finishWebhook(env,claim);
 }catch(error){await failWebhook(env,claim,error);throw error;}return json({received:true});
}

async function handleSpreadconnectWebhook(request:Request,env:Env,ctx:ExecutionContext):Promise<Response>{
 const raw=await readTextLimited(request,1024*1024);await verifySpreadconnectWebhook(raw,request.headers.get('x-sprd-signature'),env.SPREADCONNECT_WEBHOOK_SECRET);const payload=JSON.parse(raw) as Record<string,any>,eventType=String(payload.eventType||payload.type||payload.event||''),providerEventId=String(payload.id||payload.eventId||await sha256Hex(raw)),claim=await claimWebhook(env,'spreadconnect',providerEventId,eventType,await sha256Hex(raw));if(!claim)return new Response('[accepted]',{status:202,headers:{'content-type':'text/plain','cache-control':'no-store'}});
 try{const data=payload.data||payload,orderData=data.order||payload.order,shipmentData=data.shipment||payload.shipment,reference=data.externalOrderReference||orderData?.externalOrderReference||shipmentData?.externalOrderReference||payload.externalOrderReference;if(reference){const order=await env.COMMERCE_DB.prepare('SELECT id FROM orders WHERE order_number=?').bind(String(reference)).first<{id:string}>();if(order?.id)ctx.waitUntil(env.FULFILLMENT_QUEUE.send({type:'RECONCILE_ORDER',orderId:order.id}));}await finishWebhook(env,claim);}catch(error){await failWebhook(env,claim,error);throw error;}return new Response('[accepted]',{status:202,headers:{'content-type':'text/plain','cache-control':'no-store'}});
}
