import type { CartItemInput, CatalogItem, Env, ProviderName } from '../types.js';
import { badRequest, notFound } from '../lib/errors.js';
import { randomId } from '../lib/crypto.js';

interface VariantRow { product_id:string;variant_id:string;sku:string;product_name:string;variant_name:string|null;provider:string;provider_product_id:string|null;provider_sku:string|null;product_price:number;variant_price:number|null;currency:string;product_active:number;variant_active:number; }
const ACTIVE_PROVIDERS=new Set<ProviderName>(['kunaki','spreadconnect']);
const MAX_UNIT_PRICE_CENTS=10_000_000;

export async function resolveCart(env:Env,requested:CartItemInput[]):Promise<CatalogItem[]>{
 if(!Array.isArray(requested)||requested.length===0)throw badRequest('Cart must contain at least one item');if(requested.length>50)throw badRequest('Cart contains too many line items');
 const aggregated=new Map<string,number>();for(const raw of requested){const sku=String(raw?.sku||'').trim();const quantity=Number(raw?.quantity);if(!sku||sku.length>160||!Number.isInteger(quantity)||quantity<1||quantity>25)throw badRequest('Invalid cart item');const next=(aggregated.get(sku)||0)+quantity;if(next>25)throw badRequest(`Quantity limit exceeded for SKU: ${sku}`);aggregated.set(sku,next);}const totalQuantity=[...aggregated.values()].reduce((sum,quantity)=>sum+quantity,0);if(totalQuantity>100)throw badRequest('Cart contains too many total units');
 const normalized=[...aggregated.entries()].map(([sku,quantity])=>({sku,quantity}));const unique=normalized.map(item=>item.sku);const placeholders=unique.map(()=>'?').join(',');const rows=await env.COMMERCE_DB.prepare(`SELECT p.id product_id,v.id variant_id,v.sku,p.name product_name,v.name variant_name,p.provider,p.provider_product_id,v.provider_sku,p.retail_price product_price,v.retail_price variant_price,p.currency,p.active product_active,v.active variant_active FROM product_variants v JOIN products p ON p.id=v.product_id WHERE v.sku IN (${placeholders})`).bind(...unique).all<VariantRow>();const map=new Map((rows.results||[]).map(row=>[row.sku,row]));
 return normalized.map(item=>{const row=map.get(item.sku);if(!row||!row.product_active||!row.variant_active)throw badRequest(`SKU is unavailable: ${item.sku}`);const provider=row.provider as ProviderName;if(!ACTIVE_PROVIDERS.has(provider))throw badRequest(`SKU is not available through an active fulfillment provider: ${item.sku}`);if(provider==='kunaki'&&!row.provider_product_id)throw badRequest(`Kunaki product mapping is incomplete for SKU: ${item.sku}`);if(provider==='spreadconnect'&&!row.provider_sku)throw badRequest(`Spreadconnect variant mapping is incomplete for SKU: ${item.sku}`);const unitPrice=row.variant_price??row.product_price;if(!Number.isSafeInteger(unitPrice)||unitPrice<0||unitPrice>MAX_UNIT_PRICE_CENTS)throw badRequest(`SKU has an invalid configured price: ${item.sku}`);return{productId:row.product_id,variantId:row.variant_id,sku:row.sku,productName:row.product_name,variantName:row.variant_name||undefined,provider,providerProductId:row.provider_product_id||undefined,providerSku:row.provider_sku||undefined,unitPrice,currency:row.currency,quantity:item.quantity};});
}

export async function listCatalog(env:Env):Promise<unknown[]>{const result=await env.COMMERCE_DB.prepare(`SELECT p.id product_id,p.sku product_sku,p.name,p.description,p.retail_price,p.currency,v.id variant_id,v.sku,v.name variant_name,v.retail_price variant_price,v.size,v.color FROM products p JOIN product_variants v ON v.product_id=p.id WHERE p.active=1 AND v.active=1 AND p.provider IN ('kunaki','spreadconnect') ORDER BY p.name,v.name`).all();return result.results||[];}

export interface ProductUpsert{id?:string;sku:string;name:string;description?:string;retailPrice:number;currency?:string;provider:ProviderName;providerProductId?:string;active?:boolean;}
export async function upsertProduct(env:Env,input:ProductUpsert):Promise<string>{const provider=String(input.provider||'') as ProviderName;const active=input.active!==false;const currency=(input.currency||'usd').trim().toLowerCase();if(!input.sku?.trim()||input.sku.trim().length>160||!input.name?.trim()||input.name.trim().length>250||!Number.isSafeInteger(input.retailPrice)||input.retailPrice<0||input.retailPrice>MAX_UNIT_PRICE_CENTS)throw badRequest('Invalid product');if(input.description&&input.description.length>10000)throw badRequest('Product description is too long');if(!/^[a-z]{3}$/.test(currency))throw badRequest('Product currency must be a three-letter ISO currency code');if(!ACTIVE_PROVIDERS.has(provider))throw badRequest(`Fulfillment provider is not enabled: ${provider||'missing'}`);if(active&&provider==='kunaki'&&!input.providerProductId?.trim())throw badRequest('Active Kunaki products require providerProductId');
 const id=input.id||randomId('prod'),now=new Date().toISOString();await env.COMMERCE_DB.prepare(`INSERT INTO products (id,sku,name,description,retail_price,currency,provider,provider_product_id,active,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(sku) DO UPDATE SET name=excluded.name,description=excluded.description,retail_price=excluded.retail_price,currency=excluded.currency,provider=excluded.provider,provider_product_id=excluded.provider_product_id,active=excluded.active,updated_at=excluded.updated_at`).bind(id,input.sku.trim(),input.name.trim(),input.description||null,input.retailPrice,currency,provider,input.providerProductId?.trim()||null,active?1:0,now,now).run();const row=await env.COMMERCE_DB.prepare('SELECT id FROM products WHERE sku=?').bind(input.sku.trim()).first<{id:string}>();return row?.id||id;}

export interface VariantUpsert{id?:string;productId:string;sku:string;name?:string;size?:string;color?:string;providerSku?:string;retailPrice?:number|null;active?:boolean;}
export async function upsertVariant(env:Env,input:VariantUpsert):Promise<string>{if(!input.productId||!input.sku?.trim()||input.sku.trim().length>160)throw badRequest('Invalid variant');if(input.name&&input.name.length>250)throw badRequest('Variant name is too long');if(input.size&&input.size.length>100)throw badRequest('Variant size is too long');if(input.color&&input.color.length>100)throw badRequest('Variant color is too long');if(input.retailPrice!==undefined&&input.retailPrice!==null&&(!Number.isSafeInteger(input.retailPrice)||input.retailPrice<0||input.retailPrice>MAX_UNIT_PRICE_CENTS))throw badRequest('Invalid variant price');const product=await env.COMMERCE_DB.prepare('SELECT id,provider,active FROM products WHERE id=?').bind(input.productId).first<{id:string;provider:ProviderName;active:number}>();if(!product)throw notFound('Product not found');const active=input.active!==false;if(active&&product.provider==='spreadconnect'&&!input.providerSku?.trim())throw badRequest('Active Spreadconnect variants require providerSku');const id=input.id||randomId('var'),now=new Date().toISOString();await env.COMMERCE_DB.prepare(`INSERT INTO product_variants (id,product_id,sku,name,size,color,provider_sku,retail_price,active,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(sku) DO UPDATE SET product_id=excluded.product_id,name=excluded.name,size=excluded.size,color=excluded.color,provider_sku=excluded.provider_sku,retail_price=excluded.retail_price,active=excluded.active,updated_at=excluded.updated_at`).bind(id,input.productId,input.sku.trim(),input.name||null,input.size||null,input.color||null,input.providerSku?.trim()||null,input.retailPrice??null,active?1:0,now,now).run();const row=await env.COMMERCE_DB.prepare('SELECT id FROM product_variants WHERE sku=?').bind(input.sku.trim()).first<{id:string}>();return row?.id||id;}
