import type { FulfillmentProvider,FulfillmentInput,FulfillmentResult,ShipmentResult } from './types.js';
import type { Address,CatalogItem,Contact,Env,ProviderQuote } from '../types.js';
import { inferTier } from './types.js';
import { upstream } from '../lib/errors.js';
interface SpodOrder{id:number|string;state?:string;shipping?:{price?:{amount?:number;currency?:string}}}
interface SpodShipping{id:string;name?:string;company?:string;description?:string;price?:{amount?:number;currency?:string}}
async function spod<T>(env:Env,path:string,init:RequestInit={}):Promise<T>{const res=await fetch(`${env.SPREADCONNECT_BASE_URL.replace(/\/$/,'')}${path}`,{...init,signal:AbortSignal.timeout(20_000),headers:{'content-type':'application/json','X-SPOD-ACCESS-TOKEN':env.SPREADCONNECT_ACCESS_TOKEN,...(init.headers||{})}});const text=await res.text();if(text.length>2_000_000)throw upstream('Spreadconnect response exceeded safe size');let body:unknown;try{body=text?JSON.parse(text):undefined}catch{body=text.slice(0,4000)}if(!res.ok)throw upstream(`Spreadconnect HTTP ${res.status}`,body);return body as T;}
function spodAddress(a:Address){return{firstName:a.firstName,lastName:a.lastName,company:a.company||undefined,street:a.address1,streetAnnex:a.address2||undefined,city:a.city,state:a.state||undefined,country:a.country.toUpperCase(),zipCode:a.postalCode};}
function createPayload(args:{reference:string;items:CatalogItem[];address:Address;contact:Contact;state?:'NEW'|'CONFIRMED'}){return{externalOrderReference:args.reference,externalOrderName:args.reference,state:args.state||'NEW',email:args.contact.email,phone:args.contact.phone,orderItems:args.items.map(i=>{if(!i.providerSku)throw upstream(`Spreadconnect SKU missing for ${i.sku}`);return{sku:i.providerSku,quantity:i.quantity,externalOrderItemReference:i.sku,customerPrice:{amount:(i.unitPrice*i.quantity)/100,currency:i.currency.toUpperCase()}}}),shipping:{address:spodAddress(args.address),customerPrice:{amount:0,currency:args.items[0]?.currency.toUpperCase()||'USD'}}};}
export const spreadconnectProvider:FulfillmentProvider={name:'spreadconnect',
 async quoteShipping(env,args:{quoteId:string;items:CatalogItem[];address:Address;contact:Contact}):Promise<ProviderQuote>{const draft=await spod<SpodOrder>(env,'/orders',{method:'POST',body:JSON.stringify(createPayload({reference:`HHE-QUOTE-${args.quoteId}`,items:args.items,address:args.address,contact:args.contact}))});if(!draft?.id)throw upstream('Spreadconnect did not return a draft order id');const shipping=await spod<SpodShipping[]>(env,`/orders/${encodeURIComponent(String(draft.id))}/shippingTypes`);const options=(shipping||[]).map(s=>{const name=[s.company,s.name].filter(Boolean).join(' ')||`Spreadconnect ${s.id}`;const amount=Number(s.price?.amount||0);const option={provider:'spreadconnect' as const,id:String(s.id),name,price:Math.round(amount*100),currency:(s.price?.currency||env.CURRENCY).toLowerCase(),metadata:{company:s.company,description:s.description}};return{...option,tierHint:inferTier(option)}});if(!options.length){await this.cleanupDraft?.(env,String(draft.id));throw upstream('Spreadconnect returned no shipping options');}return{provider:'spreadconnect',draftOrderId:String(draft.id),options};},
 async fulfill(env,input:FulfillmentInput):Promise<FulfillmentResult>{let providerOrderId=input.draftOrderId;if(!providerOrderId){const created=await spod<SpodOrder>(env,'/orders',{method:'POST',body:JSON.stringify(createPayload({reference:input.orderNumber,items:input.items,address:input.address,contact:input.contact}))});if(!created?.id)throw upstream('Spreadconnect did not return an order id');providerOrderId=String(created.id);}else{await spod(env,`/orders/${encodeURIComponent(providerOrderId)}`,{method:'PUT',body:JSON.stringify(createPayload({reference:input.orderNumber,items:input.items,address:input.address,contact:input.contact}))});}await spod(env,`/orders/${encodeURIComponent(providerOrderId)}/shippingType`,{method:'POST',body:JSON.stringify({id:input.shippingSelection.optionId})});const confirmed=await spod<SpodOrder>(env,`/orders/${encodeURIComponent(providerOrderId)}/confirm`,{method:'POST'});return{providerOrderId,status:(confirmed?.state||'confirmed').toLowerCase(),raw:confirmed};},
 async getStatus(env,providerOrderId){const order=await spod<SpodOrder>(env,`/orders/${encodeURIComponent(providerOrderId)}`);return{status:(order.state||'unknown').toLowerCase(),raw:order};},
 async getShipments(env,providerOrderId):Promise<ShipmentResult[]>{const rows=await spod<Array<Record<string,unknown>>>(env,`/orders/${encodeURIComponent(providerOrderId)}/shipments`);const out:ShipmentResult[]=[];for(const row of rows||[]){const rowId=String(row.id||providerOrderId),tracking=Array.isArray(row.tracking)?row.tracking as Array<Record<string,unknown>>:[],status=String(row.status||row.state||'shipped').toLowerCase();if(!tracking.length)out.push({id:rowId,status,raw:row});for(const t of tracking)out.push({id:`${rowId}:${String(t.code||'untracked')}`,trackingNumber:t.code?String(t.code):undefined,trackingUrl:t.url?String(t.url):undefined,status,raw:row});}return out;},
 async cleanupDraft(env,providerOrderId){await spod(env,`/orders/${encodeURIComponent(providerOrderId)}/cancel`,{method:'POST'});},
 async cancel(env,providerOrderId){const result=await spod<SpodOrder>(env,`/orders/${encodeURIComponent(providerOrderId)}/cancel`,{method:'POST'});return{status:(result?.state||'cancelled').toLowerCase(),raw:result};}
};
