import type { Address,Env,HheShippingOption } from '../types.js';
import { badRequest,conflict,notFound,upstream } from '../lib/errors.js';
import { bytesToHex,hmacSha256,randomId,sha256Hex } from '../lib/crypto.js';
import { createStripeCheckout } from '../stripe/client.js';
import { audit } from '../lib/audit.js';
interface QuoteRow{id:string;status:string;items_json:string;address_json:string;contact_json:string;provider_quotes_json:string;options_json:string;selected_option_id:string|null;order_id:string|null;expires_at:string}
function orderNumber(){const d=new Date();const date=`${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,'0')}${String(d.getUTCDate()).padStart(2,'0')}`;return`HHE-${date}-${crypto.randomUUID().replaceAll('-','').slice(0,16).toUpperCase()}`;}
async function orderAccessToken(env:Env,orderId:string):Promise<string>{if(!env.ORDER_ACCESS_SECRET||env.ORDER_ACCESS_SECRET.length<32)throw upstream('Order access token secret is not configured');return`access_${bytesToHex(await hmacSha256(`hhe-order-access:${orderId}`,env.ORDER_ACCESS_SECRET))}`;}
export async function createCheckout(env:Env,quoteId:string,optionId:string){
 const quote=await env.COMMERCE_DB.prepare('SELECT * FROM shipping_quotes WHERE id=?').bind(quoteId).first<QuoteRow>();if(!quote)throw notFound('Shipping quote not found');
 const remainingMs=Date.parse(quote.expires_at)-Date.now();if(remainingMs<=0)throw conflict('Shipping quote has expired');if(remainingMs<31*60_000)throw conflict('Shipping quote is too close to expiry to open a secure Checkout Session. Refresh shipping rates and try again.');
 if(quote.status==='reserved'&&quote.order_id){const existing=await env.COMMERCE_DB.prepare('SELECT id,order_number,public_token,shipping_option_id,stripe_checkout_session_id,stripe_checkout_url FROM orders WHERE id=?').bind(quote.order_id).first<{id:string;order_number:string;public_token:string;shipping_option_id:string;stripe_checkout_session_id:string|null;stripe_checkout_url:string|null}>();if(!existing)throw conflict('Reserved quote is missing its order');if(existing.shipping_option_id!==optionId)throw conflict('Shipping quote is already reserved with another option');const token=await orderAccessToken(env,existing.id),tokenHash=await sha256Hex(token);if(!existing.public_token||existing.public_token!==tokenHash)await env.COMMERCE_DB.prepare('UPDATE orders SET public_token=? WHERE id=?').bind(tokenHash,existing.id).run();if(existing.stripe_checkout_session_id)return{orderNumber:existing.order_number,publicToken:token,checkoutSessionId:existing.stripe_checkout_session_id,checkoutUrl:existing.stripe_checkout_url,reused:true};throw conflict('Checkout Session creation was interrupted. Refresh shipping rates before retrying.');}
 if(quote.status!=='open')throw conflict('Shipping quote is no longer available');
 const items=JSON.parse(quote.items_json) as Array<any>;const contact=JSON.parse(quote.contact_json) as {email:string;phone:string};const options=JSON.parse(quote.options_json) as HheShippingOption[];const selected=options.find(o=>o.id===optionId);if(!selected)throw badRequest('Unknown shipping option');
 const subtotal=items.reduce((s:number,i:any)=>s+i.unitPrice*i.quantity,0);const id=randomId('ord'),number=orderNumber(),token=await orderAccessToken(env,id),tokenHash=await sha256Hex(token),now=new Date().toISOString();
 const statements:D1PreparedStatement[]=[env.COMMERCE_DB.prepare(`INSERT INTO orders (id,order_number,public_token,customer_email,customer_phone,status,payment_status,fulfillment_status,currency,subtotal,shipping_total,tax_total,grand_total,shipping_quote_id,shipping_option_id,address_json,created_at,updated_at) VALUES (?, ?, ?, ?, ?, 'pending_payment', 'unpaid', 'unfulfilled', ?, ?, ?, 0, ?, ?, ?, ?, ?, ?)`).bind(id,number,tokenHash,contact.email,contact.phone,items[0]?.currency||env.CURRENCY,subtotal,selected.price,subtotal+selected.price,quoteId,selected.id,quote.address_json,now,now)];
 for(const i of items)statements.push(env.COMMERCE_DB.prepare(`INSERT INTO order_items (id,order_id,product_id,variant_id,sku,name,quantity,unit_price,provider,provider_product_id,provider_sku) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).bind(randomId('item'),id,i.productId,i.variantId,i.sku,`${i.productName}${i.variantName?` - ${i.variantName}`:''}`,i.quantity,i.unitPrice,i.provider,i.providerProductId||null,i.providerSku||null));
 statements.push(env.COMMERCE_DB.prepare(`UPDATE shipping_quotes SET status='reserved',selected_option_id=?,order_id=? WHERE id=? AND status='open'`).bind(selected.id,id,quoteId));
 try{await env.COMMERCE_DB.batch(statements);}catch(error){const raced=await env.COMMERCE_DB.prepare('SELECT order_id FROM shipping_quotes WHERE id=?').bind(quoteId).first<{order_id:string|null}>();if(raced?.order_id)return createCheckout(env,quoteId,optionId);throw error;}
 await audit(env,{actorType:'customer',action:'checkout.reserved',entityType:'order',entityId:id,metadata:{quoteId,shippingOptionId:optionId}});return resumeStripe(env,quote,id,number,token,optionId);
}
async function resumeStripe(env:Env,quote:QuoteRow,orderId:string,number:string,token:string,optionId:string){const items=JSON.parse(quote.items_json) as Array<any>;const contact=JSON.parse(quote.contact_json) as {email:string;phone:string};const address=JSON.parse(quote.address_json) as Address;const options=JSON.parse(quote.options_json) as HheShippingOption[];const selected=options.find(o=>o.id===optionId);if(!selected)throw badRequest('Unknown shipping option');try{const session=await createStripeCheckout(env,{orderId,orderNumber:number,email:contact.email,address,lines:items.map((i:any)=>({name:`${i.productName}${i.variantName?` - ${i.variantName}`:''}`,sku:i.sku,unitAmount:i.unitPrice,quantity:i.quantity,currency:i.currency})),shipping:{name:selected.name,amount:selected.price,currency:selected.currency,minDays:selected.minDays,maxDays:selected.maxDays},expiresAtEpoch:Math.floor(Date.parse(quote.expires_at)/1000)});await env.COMMERCE_DB.prepare('UPDATE orders SET stripe_checkout_session_id=?,stripe_checkout_url=?,updated_at=? WHERE id=?').bind(session.id,session.url||null,new Date().toISOString(),orderId).run();return{orderNumber:number,publicToken:token,checkoutSessionId:session.id,checkoutUrl:session.url};}catch(error){await env.COMMERCE_DB.prepare(`UPDATE orders SET exception_code='stripe_session_create_failed',exception_detail=?,updated_at=? WHERE id=?`).bind(String(error).slice(0,2000),new Date().toISOString(),orderId).run();throw error;}}
