import type { Address,CatalogItem,Env,HheShippingOption,ProviderQuote,ProviderName } from '../types.js';
import { getProvider } from '../providers/index.js';
import { getOrder,orderItems } from '../repositories/orders.js';
import { groupByProvider } from './shipping.js';
import { randomId } from '../lib/crypto.js';
import { audit } from '../lib/audit.js';
import { providerFailure,providerSuccess } from '../lib/provider-health.js';
interface QuoteRow{provider_quotes_json:string;options_json:string;contact_json:string}
export function normalizeProviderStatus(value:string):string{const s=value.toLowerCase();if(/deliver/.test(s))return'delivered';if(/sent|shipped|dispatched/.test(s))return'shipped';if(/production|processed|processing|confirmed|checked/.test(s))return'processing';if(/cancel/.test(s))return'cancelled';if(/issue|error|failed|reject/.test(s))return'exception';return'submitted';}
async function startAttempt(env:Env,orderId:string,groupId:string,provider:ProviderName,operation:string){const id=randomId('attempt');await env.COMMERCE_DB.prepare(`INSERT INTO fulfillment_attempts (id,order_id,fulfillment_group_id,provider,operation,status,created_at,updated_at) VALUES (?,?,?,?,?,'started',?,?)`).bind(id,orderId,groupId,provider,operation,new Date().toISOString(),new Date().toISOString()).run();return id;}
async function finishAttempt(env:Env,id:string,status:'succeeded'|'failed',providerOrderId?:string,error?:unknown){await env.COMMERCE_DB.prepare(`UPDATE fulfillment_attempts SET status=?,provider_order_id=?,error=?,updated_at=? WHERE id=?`).bind(status,providerOrderId||null,error?String(error).slice(0,2000):null,new Date().toISOString(),id).run();}
export async function fulfillOrder(env:Env,orderId:string):Promise<void>{const order=await getOrder(env,orderId);if(order.payment_status!=='paid'||order.status==='cancelled'||order.status==='expired')return;if(order.exception_code==='shipping_address_mismatch')return;const items=await orderItems(env,order.id);const quote=await env.COMMERCE_DB.prepare('SELECT provider_quotes_json,options_json,contact_json FROM shipping_quotes WHERE id=?').bind(order.shipping_quote_id).first<QuoteRow>();if(!quote)throw new Error(`Shipping quote missing for ${order.id}`);const providerQuotes=JSON.parse(quote.provider_quotes_json) as ProviderQuote[];const options=JSON.parse(quote.options_json) as HheShippingOption[];const selected=options.find(o=>o.id===order.shipping_option_id);if(!selected)throw new Error(`Selected shipping option missing for ${order.id}`);const address=JSON.parse(order.address_json) as Address;const contact=JSON.parse(quote.contact_json) as {email:string;phone:string};const groups=groupByProvider(items);
 for(const[providerName,groupItems]of groups){const providerNameTyped=providerName as ProviderName;const existing=await env.COMMERCE_DB.prepare('SELECT * FROM fulfillment_groups WHERE order_id=? AND provider=?').bind(order.id,providerName).first<Record<string,unknown>>();if(existing?.status==='cancelled')continue;if(existing?.provider_order_id)continue;if(providerName==='kunaki'&&existing?.status==='exception')continue;const groupId=existing?.id?String(existing.id):randomId('fg');if(!existing){await env.COMMERCE_DB.prepare(`INSERT INTO fulfillment_groups (id,order_id,provider,status,created_at,updated_at) VALUES (?,?,?,'queued',?,?)`).bind(groupId,order.id,providerName,new Date().toISOString(),new Date().toISOString()).run();const links=groupItems.map(i=>env.COMMERCE_DB.prepare('INSERT OR IGNORE INTO fulfillment_group_items (fulfillment_group_id,order_item_id) SELECT ?,id FROM order_items WHERE order_id=? AND sku=?').bind(groupId,order.id,i.sku));if(links.length)await env.COMMERCE_DB.batch(links);}
  const pq=providerQuotes.find(q=>q.provider===providerName);const shippingSelection=selected.providerSelections[providerName];if(!shippingSelection)throw new Error(`Provider shipping selection missing for ${providerName}`);await env.COMMERCE_DB.prepare(`UPDATE fulfillment_groups SET status='submitting',updated_at=? WHERE id=?`).bind(new Date().toISOString(),groupId).run();const attemptId=await startAttempt(env,order.id,groupId,providerNameTyped,'submit');
  try{const result=await getProvider(providerNameTyped).fulfill(env,{orderId:order.id,orderNumber:order.order_number,items:groupItems,address,contact,shippingSelection,draftOrderId:pq?.draftOrderId});await env.COMMERCE_DB.prepare(`UPDATE fulfillment_groups SET provider_order_id=?,status=?,shipping_method=?,shipping_cost=?,last_error=NULL,submitted_at=?,updated_at=? WHERE id=?`).bind(result.providerOrderId,normalizeProviderStatus(result.status),shippingSelection.name,shippingSelection.price,new Date().toISOString(),new Date().toISOString(),groupId).run();await finishAttempt(env,attemptId,'succeeded',result.providerOrderId);await providerSuccess(env,providerNameTyped,'fulfill');await audit(env,{actorType:'system',action:'fulfillment.submitted',entityType:'fulfillment_group',entityId:groupId,metadata:{provider:providerName,providerOrderId:result.providerOrderId}});
  }catch(error){const note=providerName==='kunaki'?`Kunaki submission outcome requires manual review before retry: ${String(error)}`:String(error);await env.COMMERCE_DB.prepare(`UPDATE fulfillment_groups SET status='exception',last_error=?,updated_at=? WHERE id=?`).bind(note.slice(0,4000),new Date().toISOString(),groupId).run();await finishAttempt(env,attemptId,'failed',undefined,error);await providerFailure(env,providerNameTyped,'fulfill',error);await audit(env,{actorType:'system',action:'fulfillment.failed',entityType:'fulfillment_group',entityId:groupId,metadata:{provider:providerName,error:String(error)}});if(providerName!=='kunaki')throw error;}
 }
 await env.COMMERCE_DB.prepare(`UPDATE shipping_quotes SET status='consumed' WHERE id=? AND status='reserved'`).bind(order.shipping_quote_id).run();await recomputeOrderFulfillmentStatus(env,order.id);
}
export async function reconcileOrder(env:Env,orderId:string):Promise<void>{const groups=await env.COMMERCE_DB.prepare(`SELECT * FROM fulfillment_groups WHERE order_id=? AND provider_order_id IS NOT NULL AND status NOT IN ('delivered','cancelled')`).bind(orderId).all<Record<string,unknown>>();const errors:unknown[]=[];for(const g of groups.results||[]){const providerName=String(g.provider) as ProviderName;const provider=getProvider(providerName);const providerOrderId=String(g.provider_order_id);const attempt=await startAttempt(env,orderId,String(g.id),providerName,'reconcile');try{const status=await provider.getStatus(env,providerOrderId);const normalized=normalizeProviderStatus(status.status);const now=new Date().toISOString();await env.COMMERCE_DB.prepare(`UPDATE fulfillment_groups SET status=?,last_error=NULL,shipped_at=CASE WHEN ?='shipped' AND shipped_at IS NULL THEN ? ELSE shipped_at END,delivered_at=CASE WHEN ?='delivered' AND delivered_at IS NULL THEN ? ELSE delivered_at END,updated_at=? WHERE id=?`).bind(normalized,normalized,now,normalized,now,now,String(g.id)).run();const shipments=await provider.getShipments(env,providerOrderId);for(const shipment of shipments){const ss=normalizeProviderStatus(shipment.status||'shipped');await env.COMMERCE_DB.prepare(`INSERT INTO shipments (id,order_id,fulfillment_group_id,provider,carrier,tracking_number,tracking_url,status,shipped_at,delivered_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET carrier=excluded.carrier,tracking_number=excluded.tracking_number,tracking_url=excluded.tracking_url,status=excluded.status,delivered_at=COALESCE(shipments.delivered_at,excluded.delivered_at),updated_at=excluded.updated_at`).bind(`${g.provider}:${shipment.id}`,orderId,String(g.id),providerName,shipment.carrier||null,shipment.trackingNumber||null,shipment.trackingUrl||null,ss,now,ss==='delivered'?now:null,now,now).run();}await finishAttempt(env,attempt,'succeeded',providerOrderId);await providerSuccess(env,providerName,'reconcile');}catch(error){errors.push(error);await finishAttempt(env,attempt,'failed',providerOrderId,error);await providerFailure(env,providerName,'reconcile',error);await env.COMMERCE_DB.prepare('UPDATE fulfillment_groups SET last_error=?,updated_at=? WHERE id=?').bind(String(error).slice(0,4000),new Date().toISOString(),String(g.id)).run();}}
 await recomputeOrderFulfillmentStatus(env,orderId);if(errors.length)throw new AggregateError(errors,'One or more provider reconciliations failed');}
export function computeFulfillmentStatus(statuses:string[]):string{if(!statuses.length)return'unfulfilled';if(statuses.some(s=>s==='exception'))return'exception';if(statuses.every(s=>s==='cancelled'))return'cancelled';const active=statuses.filter(s=>s!=='cancelled');if(active.length&&active.every(s=>s==='delivered'))return'delivered';if(active.some(s=>s==='delivered'))return'partially_delivered';if(active.length&&active.every(s=>s==='shipped'))return'shipped';if(active.some(s=>s==='shipped'))return'partially_shipped';if(active.some(s=>s==='processing'))return'processing';if(active.some(s=>s==='submitted'||s==='submitting'))return'submitted';if(active.some(s=>s==='queued'))return'queued';return'unfulfilled';}
export async function recomputeOrderFulfillmentStatus(env:Env,orderId:string):Promise<void>{const rows=await env.COMMERCE_DB.prepare('SELECT status FROM fulfillment_groups WHERE order_id=?').bind(orderId).all<{status:string}>();const status=computeFulfillmentStatus((rows.results||[]).map(r=>r.status));let orderStatus:string|undefined;if(status==='delivered')orderStatus='complete';else if(status==='exception')orderStatus='exception';else if(status==='cancelled')orderStatus='cancelled';await env.COMMERCE_DB.prepare(`UPDATE orders SET fulfillment_status=?,status=COALESCE(?,status),updated_at=? WHERE id=?`).bind(status,orderStatus||null,new Date().toISOString(),orderId).run();}
