import type { Address,CatalogItem,Contact,Env,HheShippingOption,ProviderQuote,ProviderShippingOption,ShippingTier } from '../types.js';
import { getProvider } from '../providers/index.js';
import { badRequest,conflict,upstream } from '../lib/errors.js';
import { randomId,sha256Hex } from '../lib/crypto.js';
import { normalizeAddress } from '../lib/address.js';
import { getShippingPolicy } from '../repositories/settings.js';
import { applyShippingPolicy } from './policy.js';
import { providerFailure,providerSuccess } from '../lib/provider-health.js';
export function groupByProvider(items:CatalogItem[]):Map<string,CatalogItem[]>{const m=new Map<string,CatalogItem[]>();for(const i of items)m.set(i.provider,[...(m.get(i.provider)||[]),i]);return m;}
function speed(o:ProviderShippingOption){return o.maxDays??o.minDays??999}function cheapest(o:ProviderShippingOption[]){return[...o].sort((a,b)=>a.price-b.price||speed(a)-speed(b))[0]}function fastest(o:ProviderShippingOption[]){return[...o].sort((a,b)=>speed(a)-speed(b)||a.price-b.price)[0]}
function select(options:ProviderShippingOption[],tier:ShippingTier){if(tier==='economy')return cheapest(options);if(tier==='express')return fastest(options);const standard=options.filter(o=>o.tierHint==='standard');if(standard.length)return cheapest(standard);const low=cheapest(options),fast=fastest(options);if(low.id===fast.id)return low;const middle=options.filter(o=>o.id!==low.id&&o.id!==fast.id);return middle.length?cheapest(middle):(speed(fast)<speed(low)?fast:low);}
export function combineProviderQuotes(providerQuotes:ProviderQuote[],currency:string):HheShippingOption[]{const tiers:ShippingTier[]=['economy','standard','express'];const built=tiers.map(tier=>{let actual=0,min=0,max=0;const selections:HheShippingOption['providerSelections']={};for(const q of providerQuotes){if(!q.options.length)throw upstream(`${q.provider} returned no shipping options`);const c=select(q.options,tier);actual+=c.price;min=Math.max(min,c.minDays||0);max=Math.max(max,c.maxDays||c.minDays||0);selections[q.provider]={optionId:c.id,name:c.name,price:c.price,metadata:c.metadata};}return{id:tier,name:`HHE ${tier[0].toUpperCase()}${tier.slice(1)}`,price:actual,actualProviderCost:actual,currency,minDays:min||undefined,maxDays:max||undefined,providerSelections:selections} satisfies HheShippingOption;});const seen=new Set<string>();return built.filter(o=>{const f=JSON.stringify(Object.entries(o.providerSelections).map(([p,s])=>[p,s.optionId]));if(seen.has(f))return false;seen.add(f);return true;});}
export async function createShippingQuote(env:Env,items:CatalogItem[],addressInput:Address,contact:Contact,requestKey?:string){
 if(!contact.email||!contact.email.includes('@'))throw badRequest('A valid email is required');if(!contact.phone)throw badRequest('Phone is required for fulfillment quotes');
 const address=normalizeAddress(addressInput);const requestHash=await sha256Hex(JSON.stringify({items:items.map(i=>({sku:i.sku,quantity:i.quantity,unitPrice:i.unitPrice,provider:i.provider})),address,contact:{email:contact.email.trim().toLowerCase(),phone:contact.phone.trim()}}));if(requestKey){const existing=await env.COMMERCE_DB.prepare(`SELECT id,expires_at,options_json,request_hash FROM shipping_quotes WHERE request_key=? AND status IN ('open','reserved') AND expires_at>?`).bind(requestKey,new Date().toISOString()).first<{id:string;expires_at:string;options_json:string;request_hash:string|null}>();if(existing){if(existing.request_hash&&existing.request_hash!==requestHash)throw conflict('Idempotency-Key was already used for a different shipping quote request');return{quoteId:existing.id,expiresAt:existing.expires_at,options:JSON.parse(existing.options_json) as HheShippingOption[],reused:true};}}
 const allowed=(env.STRIPE_ALLOWED_SHIPPING_COUNTRIES||'').split(',').map(v=>v.trim().toUpperCase()).filter(Boolean);if(allowed.length&&!allowed.includes(address.country))throw badRequest(`Shipping to ${address.country} is not enabled`);const quoteId=randomId('quote');const groups=groupByProvider(items);const providerQuotes:ProviderQuote[]=[];
 try{for(const [name,group]of groups){try{const q=await getProvider(name as CatalogItem['provider']).quoteShipping(env,{quoteId,items:group,address,contact});providerQuotes.push(q);await providerSuccess(env,name as CatalogItem['provider'],'quote');}catch(error){await providerFailure(env,name as CatalogItem['provider'],'quote',error);throw error;}}}catch(error){for(const q of providerQuotes)if(q.draftOrderId)await getProvider(q.provider).cleanupDraft?.(env,q.draftOrderId);throw error;}
 const currencies=new Set(items.map(i=>i.currency.toLowerCase()));if(currencies.size!==1)throw upstream('Mixed currencies are not supported');
 const subtotal=items.reduce((s,i)=>s+i.unitPrice*i.quantity,0);const policy=await getShippingPolicy(env);const options=applyShippingPolicy(combineProviderQuotes(providerQuotes,items[0].currency.toLowerCase()),subtotal,policy);if(!options.length)throw upstream('No HHE shipping options could be built');
 const ttl=Math.max(35,Number(env.QUOTE_TTL_MINUTES)||45);const expiresAt=new Date(Date.now()+ttl*60_000).toISOString();
 await env.COMMERCE_DB.prepare(`INSERT INTO shipping_quotes (id,status,items_json,address_json,contact_json,provider_quotes_json,options_json,request_key,request_hash,expires_at,created_at) VALUES (?,'open',?,?,?,?,?,?,?,?,?)`)
 .bind(quoteId,JSON.stringify(items),JSON.stringify(address),JSON.stringify(contact),JSON.stringify(providerQuotes),JSON.stringify(options),requestKey||null,requestHash,expiresAt,new Date().toISOString()).run();return{quoteId,expiresAt,options};
}
