import type { Env } from '../types.js';
import { badRequest,conflict,upstream } from '../lib/errors.js';
import { randomId } from '../lib/crypto.js';
import { audit } from '../lib/audit.js';
interface RefundRow{id:string;order_id:string;request_key:string;stripe_refund_id:string|null;amount:number;reason:string|null;status:string;created_at:string;updated_at:string}

async function recomputeRefundState(env:Env,orderId:string):Promise<void>{const order=await env.COMMERCE_DB.prepare('SELECT grand_total FROM orders WHERE id=?').bind(orderId).first<{grand_total:number}>();if(!order)return;const succeeded=await env.COMMERCE_DB.prepare(`SELECT COALESCE(SUM(amount),0) total FROM refunds WHERE order_id=? AND status='succeeded'`).bind(orderId).first<{total:number}>();const pending=await env.COMMERCE_DB.prepare(`SELECT COUNT(*) count FROM refunds WHERE order_id=? AND status IN ('creating','pending','requires_action')`).bind(orderId).first<{count:number}>();const total=Number(succeeded?.total||0);let status='none';if(total>=order.grand_total&&order.grand_total>0)status='full';else if(total>0)status='partial';else if(Number(pending?.count||0)>0)status='pending';await env.COMMERCE_DB.prepare('UPDATE orders SET refund_status=?,refunded_total=?,updated_at=? WHERE id=?').bind(status,total,new Date().toISOString(),orderId).run();}
export async function createRefund(env:Env,args:{orderId:string;amount?:number;reason?:string;requestKey:string}){
 if(!args.requestKey)throw badRequest('Idempotency-Key is required for refunds');const existing=await env.COMMERCE_DB.prepare('SELECT * FROM refunds WHERE request_key=?').bind(args.requestKey).first<RefundRow>();if(existing)return existing;
 const order=await env.COMMERCE_DB.prepare('SELECT id,grand_total,stripe_payment_intent_id,payment_status FROM orders WHERE id=?').bind(args.orderId).first<{id:string;grand_total:number;stripe_payment_intent_id:string|null;payment_status:string}>();if(!order)throw badRequest('Order not found');if(order.payment_status!=='paid'||!order.stripe_payment_intent_id)throw conflict('Order is not refundable through Stripe yet');
 const totals=await env.COMMERCE_DB.prepare(`SELECT COALESCE(SUM(amount),0) total FROM refunds WHERE order_id=? AND status NOT IN ('failed','canceled')`).bind(args.orderId).first<{total:number}>();const remaining=Math.max(0,order.grand_total-Number(totals?.total||0));const amount=args.amount===undefined?remaining:Number(args.amount);if(!Number.isInteger(amount)||amount<=0||amount>remaining)throw badRequest('Invalid refund amount',{remaining});
 const id=randomId('refund'),now=new Date().toISOString();await env.COMMERCE_DB.prepare(`INSERT INTO refunds (id,order_id,request_key,amount,reason,status,created_at,updated_at) VALUES (?,?,?,?,?,'creating',?,?)`).bind(id,args.orderId,args.requestKey,amount,args.reason||null,now,now).run();
 const p=new URLSearchParams({payment_intent:order.stripe_payment_intent_id,amount:String(amount),'metadata[hhe_order_id]':args.orderId,'metadata[hhe_refund_id]':id});if(args.reason)p.set('metadata[reason]',args.reason.slice(0,450));
 try{const res=await fetch('https://api.stripe.com/v1/refunds',{method:'POST',headers:{authorization:`Bearer ${env.STRIPE_SECRET_KEY}`,'content-type':'application/x-www-form-urlencoded','Idempotency-Key':`hhe-refund-${id}`},body:p.toString()});const body=await res.json() as Record<string,unknown>;if(!res.ok)throw upstream('Stripe refund failed',body);const status=String(body.status||'pending');await env.COMMERCE_DB.prepare('UPDATE refunds SET stripe_refund_id=?,status=?,updated_at=? WHERE id=?').bind(String(body.id||''),status,new Date().toISOString(),id).run();await recomputeRefundState(env,args.orderId);await audit(env,{actorType:'admin',actorId:'admin-api',action:'refund.created',entityType:'order',entityId:args.orderId,metadata:{refundId:id,amount,status}});return await env.COMMERCE_DB.prepare('SELECT * FROM refunds WHERE id=?').bind(id).first<RefundRow>();}catch(error){await env.COMMERCE_DB.prepare(`UPDATE refunds SET status='failed',last_error=?,updated_at=? WHERE id=?`).bind(String(error).slice(0,2000),new Date().toISOString(),id).run();throw error;}
}
export async function updateRefundFromWebhook(env:Env,refund:Record<string,any>):Promise<void>{const id=String(refund.metadata?.hhe_refund_id||'');if(!id)return;const row=await env.COMMERCE_DB.prepare('SELECT order_id FROM refunds WHERE id=?').bind(id).first<{order_id:string}>();if(!row)return;await env.COMMERCE_DB.prepare('UPDATE refunds SET stripe_refund_id=?,status=?,updated_at=? WHERE id=?').bind(String(refund.id||''),String(refund.status||'unknown'),new Date().toISOString(),id).run();await recomputeRefundState(env,row.order_id);}
